apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins-pipeline-operator
  template:
    metadata:
      labels:
        name: jenkins-pipeline-operator
    spec:
      serviceAccountName: jenkins-pipeline-operator
      containers:
        - name: jenkins-pipeline-operator
          # Replace this with the built image name
          image: digitalrasta/jenkins-pipeline-operator:latest
          command:
          - jenkins-pipeline-operator
          imagePullPolicy: Always
          env:
            - name: JENKINS_API_TOKEN
              value: "11ec5ec4a8cacb84e10ed10e099d473538"
            - name: JENKINS_URL
              value: "http://jenkins:8080"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jenkins-pipeline-operator"
